name: state_management_dart
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  bloc: ^8.1.4
# path: ^1.8.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
